#!/bin/bash

LIPCMS_BASE=/exper-sw/cmst3/cmssw/users/vischia/chiggs/CMSSW_5_3_9/src/LIP/TopTaus/
myFolder=${LIPCMS_BASE}/scripts/lip-batch/

cd $myFolder;

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 16  
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh 18

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 16  
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh 18

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 49



qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh 49



qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 16  
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh 18


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 16  
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh 18


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 16  
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh 18

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 16  
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh 18

#####qsub -v LIPCMS_BASE${LIPCMS_BASE}/    ./job-ttbar-unc.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-hh-higgs-bychannel.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-hh-higgs.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-qcd.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-singletop.sh
#qsub -v LIPCMS_BASE${LIPCMS_BASE}/    ./job-trigger-mht.sh
#qsub -v LIPCMS_BASE${LIPCMS_BASE}/    ./job-trigger-mhtjets.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wh-higgs-bychannel.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wh-higgs.sh


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-tbh-higgs.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-tbh-higgs-bychannel.sh


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 180 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 200 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 220 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 240 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 250 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 260 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 280 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs.sh 300 29





qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 180 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 200 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 220 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 240 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 250 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 260 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 280 29

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 2 
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel.sh 300 29





