#!/bin/bash

LIPCMS_BASE=/exper-sw/cmst3/cmssw/users/vischia/chiggs/CMSSW_5_3_9/src/LIP/TopTaus/
myFolder=${LIPCMS_BASE}/scripts/lip-batch/

cd $myFolder;

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ww.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wz.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zz.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-ddbkg.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunA.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunB.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC1.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunC2.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD1.sh 49

qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 0
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 1
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 2
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 3
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 4
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 5
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 6
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 7
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 8
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 9
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 10
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 11
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 12
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 13
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 14
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 15
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 16
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 17
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 18
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 19
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 20
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 21
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 22
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 23
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 24
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 25
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 26
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 27
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 28
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 29
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 30
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 31
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 32
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 33
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 34
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 35
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 36
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 37
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 38
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 39
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 40
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 41
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 42
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 43
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 44
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 45
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 46
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 47
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 48
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-data-RunD2.sh 49


qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wjets.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mutau.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mumu.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-emu.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-ttbar-mcbkg.sh
#qsub -v LIPCMS_BASE${LIPCMS_BASE}/    ./job-ttbar-unc.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-hh-higgs-bychannel.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-hh-higgs.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-qcd.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-singletop.sh
#qsub -v LIPCMS_BASE${LIPCMS_BASE}/    ./job-trigger-mht.sh
#qsub -v LIPCMS_BASE${LIPCMS_BASE}/    ./job-trigger-mhtjets.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wh-higgs-bychannel.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-wh-higgs.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_from50.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-zjets_10to50.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-tbh-higgs.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-tbh-higgs-bychannel.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_180.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_200.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_220.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_240.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_250.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_260.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_280.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs_300.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_180.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_200.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_220.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_240.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_250.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_260.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_280.sh
qsub -v LIPCMS_BASE=${LIPCMS_BASE}    ./job-htb-higgs-bychannel_300.sh


